name: radcure-challenge
channels:
  - simpleitk
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - cudatoolkit
  - cython
  - ipython
  - joblib
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - lifelines
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pip
  - python
  - pytorch
  - scikit-learn
  - scipy
  - seaborn
  - simpleitk
  - statsmodels
  - torchvision
  - pip:
    - pymrmre==1.0.0
    - pytorch-lightning==0.9.0
    - pyradiomics==2.2.0
    - tensorboard==2.1.1
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - tqdm==4.46.0
